[package]
name = "online-boarding-house-system"
version = "0.1.0"
description = "Online Boarding House System Laravel Application"

[dependencies]
"php/php" = "=8.3.4"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "localhost:8080", "/app/server.php"]
