<?php

return [
    'routes' => [
        'student' => [
            ['label' => 'Browse rooms', 'path' => '/student/rooms'],
            ['label' => 'Property map', 'path' => '/student/properties/map'],
            ['label' => 'Requests', 'path' => '/student/requests'],
            ['label' => 'Messages', 'path' => '/messages'],
            ['label' => 'Notifications', 'path' => '/notifications'],
            ['label' => 'Tenant onboarding', 'path' => '/student/onboarding'],
            ['label' => 'Reports', 'path' => '/student/reports'],
            ['label' => 'Profile', 'path' => '/student/profile'],
            ['label' => 'Dashboard', 'path' => '/student/dashboard'],
        ],
        'landlord' => [
            ['label' => 'Dashboard', 'path' => '/landlord/dashboard'],
            ['label' => 'Properties', 'path' => '/landlord/properties'],
            ['label' => 'Rooms', 'path' => '/landlord/rooms'],
            ['label' => 'Booking requests', 'path' => '/landlord/bookings'],
            ['label' => 'Messages', 'path' => '/landlord/messages'],
            ['label' => 'Feedback', 'path' => '/landlord/feedback'],
            ['label' => 'Tenants', 'path' => '/landlord/tenants'],
            ['label' => 'Onboarding', 'path' => '/landlord/onboarding'],
            ['label' => 'Leave requests', 'path' => '/landlord/leave-requests'],
            ['label' => 'Maintenance', 'path' => '/landlord/maintenance'],
            ['label' => 'Payments', 'path' => '/landlord/payments'],
            ['label' => 'Analytics', 'path' => '/landlord/analytics'],
            ['label' => 'Profile', 'path' => '/landlord/profile'],
            ['label' => 'Notifications', 'path' => '/notifications'],
        ],
        'admin' => [
            ['label' => 'Dashboard', 'path' => '/admin/dashboard'],
            ['label' => 'Users', 'path' => '/admin/users'],
            ['label' => 'Properties', 'path' => '/admin/properties'],
            ['label' => 'Approvals', 'path' => '/admin/properties/pending'],
            ['label' => 'Bookings', 'path' => '/admin/bookings'],
            ['label' => 'Onboardings', 'path' => '/admin/onboardings'],
            ['label' => 'Reports', 'path' => '/admin/reports'],
            ['label' => 'Notifications', 'path' => '/notifications'],
        ],
    ],
    'route_map' => [
        'student' => [
            'available rooms' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'browse rooms' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'property map' => ['label' => 'Property map', 'url' => '/student/properties/map'],
            'requests' => ['label' => 'Requests', 'url' => '/student/requests'],
            'messages' => ['label' => 'Messages', 'url' => '/messages'],
            'notifications' => ['label' => 'Notifications', 'url' => '/notifications'],
            'onboarding' => ['label' => 'Tenant onboarding', 'url' => '/student/onboarding'],
            'reports' => ['label' => 'Reports', 'url' => '/student/reports'],
            'profile' => ['label' => 'Profile', 'url' => '/student/profile'],
            'dashboard' => ['label' => 'Dashboard', 'url' => '/student/dashboard'],
        ],
        'landlord' => [
            'properties' => ['label' => 'Properties', 'url' => '/landlord/properties'],
            'rooms' => ['label' => 'Rooms', 'url' => '/landlord/rooms'],
            'booking requests' => ['label' => 'Booking requests', 'url' => '/landlord/bookings'],
            'messages' => ['label' => 'Messages', 'url' => '/landlord/messages'],
            'feedback' => ['label' => 'Feedback', 'url' => '/landlord/feedback'],
            'tenants' => ['label' => 'Tenants', 'url' => '/landlord/tenants'],
            'onboarding' => ['label' => 'Onboarding', 'url' => '/landlord/onboarding'],
            'leave requests' => ['label' => 'Leave requests', 'url' => '/landlord/leave-requests'],
            'maintenance' => ['label' => 'Maintenance', 'url' => '/landlord/maintenance'],
            'payments' => ['label' => 'Payments', 'url' => '/landlord/payments'],
            'analytics' => ['label' => 'Analytics', 'url' => '/landlord/analytics'],
            'profile' => ['label' => 'Profile', 'url' => '/landlord/profile'],
            'dashboard' => ['label' => 'Dashboard', 'url' => '/landlord/dashboard'],
            'notifications' => ['label' => 'Notifications', 'url' => '/notifications'],
        ],
        'admin' => [
            'users' => ['label' => 'Users', 'url' => '/admin/users'],
            'properties' => ['label' => 'Properties', 'url' => '/admin/properties'],
            'approvals' => ['label' => 'Approvals', 'url' => '/admin/properties/pending'],
            'bookings' => ['label' => 'Bookings', 'url' => '/admin/bookings'],
            'onboardings' => ['label' => 'Onboardings', 'url' => '/admin/onboardings'],
            'reports' => ['label' => 'Reports', 'url' => '/admin/reports'],
            'dashboard' => ['label' => 'Dashboard', 'url' => '/admin/dashboard'],
            'notifications' => ['label' => 'Notifications', 'url' => '/notifications'],
        ],
    ],
    'blocked_hints' => [
        'student' => ['landlord', 'admin'],
        'landlord' => ['admin', 'student'],
        'admin' => ['landlord', 'student'],
    ],
];
