<?php

return [
    'routes' => [
        'student' => [
            ['label' => 'Student setup', 'path' => '/student/setup'],
            ['label' => 'Browse rooms', 'path' => '/student/rooms'],
            ['label' => 'Room details', 'path' => '/student/rooms/{room}'],
            ['label' => 'Property map', 'path' => '/student/properties/map'],
            ['label' => 'Requests', 'path' => '/student/requests'],
            ['label' => 'Messages', 'path' => '/messages'],
            ['label' => 'Notifications', 'path' => '/notifications'],
            ['label' => 'Tenant onboarding', 'path' => '/student/onboarding'],
            ['label' => 'Tenant dashboard', 'path' => '/student/tenant-dashboard'],
            ['label' => 'Payments', 'path' => '/student/payments'],
            ['label' => 'Reports', 'path' => '/student/reports'],
            ['label' => 'Profile', 'path' => '/student/profile'],
            ['label' => 'Dashboard', 'path' => '/student/dashboard'],
        ],
        'landlord' => [
            ['label' => 'Dashboard', 'path' => '/landlord/dashboard'],
            ['label' => 'Setup', 'path' => '/landlord/setup'],
            ['label' => 'Properties', 'path' => '/landlord/properties'],
            ['label' => 'Rooms', 'path' => '/landlord/rooms'],
            ['label' => 'Booking requests', 'path' => '/landlord/bookings'],
            ['label' => 'Messages', 'path' => '/landlord/messages'],
            ['label' => 'Feedback', 'path' => '/landlord/feedback'],
            ['label' => 'Tenants', 'path' => '/landlord/tenants'],
            ['label' => 'Onboarding', 'path' => '/landlord/onboarding'],
            ['label' => 'Leave requests', 'path' => '/landlord/leave-requests'],
            ['label' => 'Maintenance', 'path' => '/landlord/maintenance'],
            ['label' => 'Payments', 'path' => '/landlord/payments'],
            ['label' => 'Analytics', 'path' => '/landlord/analytics'],
            ['label' => 'Profile', 'path' => '/landlord/profile'],
            ['label' => 'Notifications', 'path' => '/notifications'],
        ],
        'admin' => [
            ['label' => 'Dashboard', 'path' => '/admin/dashboard'],
            ['label' => 'Settings', 'path' => '/admin/settings'],
            ['label' => 'Users', 'path' => '/admin/users'],
            ['label' => 'Student verifications', 'path' => '/admin/student-verifications'],
            ['label' => 'Permits', 'path' => '/admin/permits'],
            ['label' => 'Properties', 'path' => '/admin/properties'],
            ['label' => 'Property approvals', 'path' => '/admin/properties/approval'],
            ['label' => 'Bookings', 'path' => '/admin/bookings'],
            ['label' => 'Boarded students', 'path' => '/admin/boarded-students'],
            ['label' => 'Onboardings', 'path' => '/admin/onboardings'],
            ['label' => 'Reports', 'path' => '/admin/reports'],
            ['label' => 'Notifications', 'path' => '/notifications'],
        ],
    ],
    'route_map' => [
        'student' => [
            'pinaka murang room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'pinakamurang room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'murang room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'murang available' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'pinaka malapit' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'pinakamalapit' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'malapit na room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'nearest room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'closest room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'available room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'available rooms' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'mag browse' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'mag-browse' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'saan makikita' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'available rooms' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'browse rooms' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'property map' => ['label' => 'Property map', 'url' => '/student/properties/map'],
            'requests' => ['label' => 'Requests', 'url' => '/student/requests'],
            'tenant dashboard' => ['label' => 'Tenant dashboard', 'url' => '/student/tenant-dashboard'],
            'my room' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            'payments' => ['label' => 'Payments', 'url' => '/student/payments'],
            'monthly payment' => ['label' => 'Payments', 'url' => '/student/payments'],
            'onboarding docs' => ['label' => 'Tenant onboarding', 'url' => '/student/onboarding'],
            'student setup' => ['label' => 'Student setup', 'url' => '/student/setup'],
            'messages' => ['label' => 'Messages', 'url' => '/messages'],
            'notifications' => ['label' => 'Notifications', 'url' => '/notifications'],
            'onboarding' => ['label' => 'Tenant onboarding', 'url' => '/student/onboarding'],
            'reports' => ['label' => 'Reports', 'url' => '/student/reports'],
            'profile' => ['label' => 'Profile', 'url' => '/student/profile'],
            'dashboard' => ['label' => 'Dashboard', 'url' => '/student/dashboard'],
        ],
        'landlord' => [
            'properties' => ['label' => 'Properties', 'url' => '/landlord/properties'],
            'rooms' => ['label' => 'Rooms', 'url' => '/landlord/rooms'],
            'booking requests' => ['label' => 'Booking requests', 'url' => '/landlord/bookings'],
            'messages' => ['label' => 'Messages', 'url' => '/landlord/messages'],
            'feedback' => ['label' => 'Feedback', 'url' => '/landlord/feedback'],
            'tenants' => ['label' => 'Tenants', 'url' => '/landlord/tenants'],
            'onboarding' => ['label' => 'Onboarding', 'url' => '/landlord/onboarding'],
            'leave requests' => ['label' => 'Leave requests', 'url' => '/landlord/leave-requests'],
            'maintenance' => ['label' => 'Maintenance', 'url' => '/landlord/maintenance'],
            'payments' => ['label' => 'Payments', 'url' => '/landlord/payments'],
            'analytics' => ['label' => 'Analytics', 'url' => '/landlord/analytics'],
            'setup' => ['label' => 'Setup', 'url' => '/landlord/setup'],
            'profile' => ['label' => 'Profile', 'url' => '/landlord/profile'],
            'dashboard' => ['label' => 'Dashboard', 'url' => '/landlord/dashboard'],
            'notifications' => ['label' => 'Notifications', 'url' => '/notifications'],
        ],
        'admin' => [
            'users' => ['label' => 'Users', 'url' => '/admin/users'],
            'properties' => ['label' => 'Properties', 'url' => '/admin/properties'],
            'property approval' => ['label' => 'Property approvals', 'url' => '/admin/properties/approval'],
            'permits' => ['label' => 'Permits', 'url' => '/admin/permits'],
            'student verification' => ['label' => 'Student verifications', 'url' => '/admin/student-verifications'],
            'bookings' => ['label' => 'Bookings', 'url' => '/admin/bookings'],
            'boarded students' => ['label' => 'Boarded students', 'url' => '/admin/boarded-students'],
            'onboardings' => ['label' => 'Onboardings', 'url' => '/admin/onboardings'],
            'reports' => ['label' => 'Reports', 'url' => '/admin/reports'],
            'dashboard' => ['label' => 'Dashboard', 'url' => '/admin/dashboard'],
            'settings' => ['label' => 'Settings', 'url' => '/admin/settings'],
            'notifications' => ['label' => 'Notifications', 'url' => '/notifications'],
        ],
    ],
    'intent_types' => [
        'navigation' => ['saan', 'nasaan', 'where', 'where can', 'saan makikita', 'saan pupunta', 'open', 'page', 'link'],
        'explanation' => ['explain', 'pa explain', 'ano ibig sabihin', 'what is', 'meaning', 'ibig sabihin', 'para saan', 'ano yung'],
        'steps' => ['paano', 'how', 'steps', 'step', 'guide', 'procedure', 'process', 'paano gawin', 'paano ako', 'bigyan mo ko ng steps'],
    ],
    'local_intents' => [
        'student' => [
            'payments' => [
                'keywords' => ['bayad', 'magbayad', 'pagbabayad', 'payment', 'payments', 'billing', 'dues', 'monthly payment', 'saan ako magbabayad', 'paano magbayad', 'saan makikita payment'],
                'responses' => [
                    'nav' => 'You can handle payments in Student Portal > Payments: /student/payments.',
                    'explain' => 'Monthly payments are the recurring rental payments that a tenant needs to settle for their assigned room. In the system, the Payments page lets you view payment records, check pending or overdue payments, and submit payment proof or payment details if required by the landlord.',
                    'steps' => "To pay or submit a payment:\n1. Go to Student Portal > Payments.\n2. Check the payment record or monthly due listed for your room.\n3. Open the payment item you need to settle.\n4. Follow the displayed payment instructions or landlord payment method.\n5. Upload proof of payment or submit the required payment details if the system asks for it.\n6. Wait for the landlord/admin to review or update the payment status.",
                ],
                'action' => ['label' => 'Payments', 'url' => '/student/payments'],
            ],
            'rooms' => [
                'keywords' => ['room', 'rooms', 'browse room', 'available room', 'boarding house', 'saan makikita room', 'saan ako maghahanap'],
                'reply' => 'Browse rooms in Student Portal > Browse Rooms: /student/rooms.',
                'action' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            ],
            'property_map' => [
                'keywords' => ['property map'],
                'reply' => 'You can open the Property Map here: /student/properties/map.',
                'action' => ['label' => 'Property map', 'url' => '/student/properties/map'],
            ],
            'booking' => [
                'keywords' => ['booking', 'book', 'magbook', 'request booking', 'reservation', 'booking request'],
                'responses' => [
                    'nav' => 'Booking requests are submitted from a room details page. Go to Browse Rooms, open a room, then use the booking action.',
                    'explain' => 'A booking request is the student\'s request to reserve or apply for a room. It is not yet a confirmed stay. The landlord must review the request first. If approved, the student can continue to tenant onboarding. If rejected, the student may browse other rooms and submit another request.',
                    'steps' => "To submit a booking request:\n1. Go to Student Portal > Browse Rooms.\n2. Open the room you want to check.\n3. Review the room details, price, capacity, and availability.\n4. Click the booking/request action if available.\n5. Submit the required details.\n6. Wait for the landlord to approve or reject the request.\n7. If approved, continue to Tenant Onboarding.",
                ],
                'action' => ['label' => 'Browse rooms', 'url' => '/student/rooms'],
            ],
            'onboarding' => [
                'keywords' => ['onboarding', 'tenant onboarding', 'documents', 'upload documents', 'contract', 'deposit', 'requirements'],
                'responses' => [
                    'nav' => 'Approved students complete onboarding in Student Portal > Tenant Onboarding: /student/onboarding.',
                    'explain' => 'Tenant onboarding happens after a booking is approved. It typically includes submitting required documents, reviewing and signing the contract, and paying a deposit if required by the landlord.',
                    'steps' => "To complete tenant onboarding:\n1. Go to Student Portal > Tenant Onboarding.\n2. Check the required onboarding items.\n3. Upload required documents if requested.\n4. Review and sign the contract if available.\n5. Submit deposit/payment proof if required.\n6. Wait for landlord review or completion status.",
                ],
                'action' => ['label' => 'Tenant onboarding', 'url' => '/student/onboarding'],
            ],
            'reports' => [
                'keywords' => ['report', 'concern', 'complaint', 'feedback', 'issue', 'problema', 'reklamo'],
                'responses' => [
                    'nav' => 'Submit concerns through Student Portal > Reports: /student/reports.',
                    'explain' => 'Reports/concerns are used to submit issues about your room, boarding house, landlord communication, maintenance, safety, or other concerns.',
                    'steps' => "To submit a report/concern:\n1. Go to the Reports page.\n2. Choose the type of concern.\n3. Write a clear description.\n4. Attach proof if available.\n5. Submit and wait for review/response.",
                ],
                'action' => ['label' => 'Reports', 'url' => '/student/reports'],
            ],
            'messages' => [
                'keywords' => ['message', 'chat', 'contact landlord', 'landlord message'],
                'reply' => 'You can message landlords in Messages: /messages.',
                'action' => ['label' => 'Messages', 'url' => '/messages'],
            ],
            'notifications' => [
                'keywords' => ['notification', 'notifications', 'alert', 'updates'],
                'reply' => 'Check Notifications here: /notifications.',
                'action' => ['label' => 'Notifications', 'url' => '/notifications'],
            ],
        ],
        'landlord' => [
            'payments' => [
                'keywords' => ['bayad', 'payment', 'payments', 'billing', 'dues', 'monthly payment'],
                'responses' => [
                    'nav' => 'Track tenant payments in Landlord Portal > Payments: /landlord/payments.',
                    'explain' => 'Landlord payments are for monitoring tenant monthly dues, reviewing payment submissions, and tracking pending or overdue balances.',
                    'steps' => "To manage payments as a landlord:\n1. Go to Landlord Portal > Payments.\n2. Review tenant payment records.\n3. Check pending/overdue payments.\n4. Open a payment record.\n5. Verify submitted payment details or proof.\n6. Update or monitor status based on available actions.",
                ],
                'action' => ['label' => 'Payments', 'url' => '/landlord/payments'],
            ],
            'properties' => [
                'keywords' => ['property', 'properties', 'manage property', 'add property'],
                'reply' => 'Manage properties in Landlord Portal > Properties: /landlord/properties.',
                'action' => ['label' => 'Properties', 'url' => '/landlord/properties'],
            ],
            'rooms' => [
                'keywords' => ['room management', 'add room', 'edit room', 'rooms'],
                'reply' => 'Manage rooms in Landlord Portal > Rooms: /landlord/rooms.',
                'action' => ['label' => 'Rooms', 'url' => '/landlord/rooms'],
            ],
            'booking_requests' => [
                'keywords' => ['booking', 'booking request', 'request booking', 'reservation'],
                'reply' => 'Review booking requests in Landlord Portal > Booking Requests: /landlord/bookings.',
                'action' => ['label' => 'Booking requests', 'url' => '/landlord/bookings'],
            ],
            'onboarding' => [
                'keywords' => ['onboarding', 'tenant onboarding', 'documents', 'contract'],
                'reply' => 'Review tenant onboarding records in Landlord Portal > Onboarding: /landlord/onboarding.',
                'action' => ['label' => 'Onboarding', 'url' => '/landlord/onboarding'],
            ],
            'leave_requests' => [
                'keywords' => ['leave request', 'leave', 'move out'],
                'reply' => 'Handle leave requests in Landlord Portal > Leave Requests: /landlord/leave-requests.',
                'action' => ['label' => 'Leave requests', 'url' => '/landlord/leave-requests'],
            ],
            'permit' => [
                'keywords' => ['permit', 'business permit'],
                'reply' => 'Business permit upload is optional and can be submitted for admin review via Landlord Setup: /landlord/setup.',
                'action' => ['label' => 'Landlord setup', 'url' => '/landlord/setup'],
            ],
            'messages' => [
                'keywords' => ['message', 'chat', 'student message'],
                'reply' => 'You can message students in Landlord Portal > Messages: /landlord/messages.',
                'action' => ['label' => 'Messages', 'url' => '/landlord/messages'],
            ],
        ],
        'admin' => [
            'users' => [
                'keywords' => ['users', 'user management'],
                'reply' => 'Manage users in Admin Portal > Users: /admin/users.',
                'action' => ['label' => 'Users', 'url' => '/admin/users'],
            ],
            'student_verification' => [
                'keywords' => ['verify student', 'student verification'],
                'reply' => 'Review student verification documents in Admin Portal > Student Verifications: /admin/student-verifications.',
                'action' => ['label' => 'Student verifications', 'url' => '/admin/student-verifications'],
            ],
            'permits' => [
                'keywords' => ['permit', 'business permit'],
                'reply' => 'Review landlord permits in Admin Portal > Permits: /admin/permits.',
                'action' => ['label' => 'Permits', 'url' => '/admin/permits'],
            ],
            'property_approval' => [
                'keywords' => ['approve property', 'property approval'],
                'reply' => 'Review property listings in Admin Portal > Property Approvals: /admin/properties/approval.',
                'action' => ['label' => 'Property approvals', 'url' => '/admin/properties/approval'],
            ],
            'reports' => [
                'keywords' => ['report', 'reports'],
                'reply' => 'Handle concerns in Admin Portal > Reports: /admin/reports.',
                'action' => ['label' => 'Reports', 'url' => '/admin/reports'],
            ],
            'boarded_students' => [
                'keywords' => ['boarded students', 'boarded'],
                'reply' => 'View boarded students in Admin Portal: /admin/boarded-students.',
                'action' => ['label' => 'Boarded students', 'url' => '/admin/boarded-students'],
            ],
        ],
    ],
    'dictionary' => [
        'system_overview' => [
            'Online Boarding House System (OBHS/e-BHMS) for student room discovery, booking, and tenancy management.',
            'Roles are student, landlord, admin. Routes and actions are role-scoped.',
        ],
        'role_definitions' => [
            'student: browse rooms, request bookings, onboarding, payments, reports, and profile management.',
            'tenant_student: student with an active approved stay and onboarding workflow.',
            'landlord: manage properties, rooms, bookings, tenants, payments, and onboarding reviews.',
            'admin: oversee users, verifications, property approvals, bookings, reports, and settings.',
        ],
        'student_features' => [
            'Dashboard overview and notifications.',
            'Browse rooms and view room details; use property map.',
            'Send inquiries to landlords from room pages.',
            'Submit booking requests and view/cancel requests.',
            'Complete student setup/verification requirements.',
            'Tenant onboarding steps: upload documents, sign contract, pay deposit if required.',
            'Submit reports/concerns and view responses.',
            'Manage profile and password.',
        ],
        'tenant_student_features' => [
            'Tenant dashboard with current stay summary and My Room access.',
            'View assigned room and onboarding status.',
            'Submit leave requests and message landlord.',
            'View and submit monthly payments.',
            'Submit room feedback and reports.',
            'Browse other rooms for future reference (booking disabled during active stay).',
        ],
        'landlord_features' => [
            'Complete setup profile and billing preferences; business permit upload is optional.',
            'Create and manage properties and rooms (pricing, capacity, availability).',
            'Review booking requests and approve/reject.',
            'Manage tenants, maintenance status, and leave requests.',
            'Review onboarding documents and sign contracts.',
            'Manage monthly payment records and send reminders.',
            'View analytics and feedback.',
        ],
        'admin_features' => [
            'Admin dashboard and settings.',
            'Manage users by role and review landlord details.',
            'Approve/reject student verifications.',
            'Review landlord business permits when uploaded.',
            'Approve/reject property listings and monitor bookings.',
            'View boarded students and onboarding records.',
            'Manage reports/concerns and update statuses.',
        ],
        'shared_features' => [
            'Notifications and in-app messages (role-scoped).',
            'Chatbot assistance for product navigation and workflows.',
        ],
        'workflows' => [
            'Student registration -> email verification -> student setup/verification -> dashboard access.',
            'Browse rooms -> view details -> inquire -> submit booking request.',
            'Landlord reviews booking -> approve/reject -> onboarding starts if approved.',
            'Tenant onboarding -> upload documents -> sign contract -> pay deposit if required.',
            'Monthly payments tracked by landlord; student submits payment proofs.',
            'Leave request: tenant submits -> landlord approves/rejects.',
            'Landlord setup: profile + billing; permit optional and not a blocker.',
            'Property approval: landlord submits -> admin approves/rejects.',
            'Reports: student submits -> admin reviews and responds.',
        ],
        'page_dictionary' => [
            '/student/dashboard: student overview and quick actions.',
            '/student/tenant-dashboard: tenant stay overview.',
            '/student/rooms: browse rooms.',
            '/student/rooms/{room}: room details, inquiry, and booking (if allowed).',
            '/student/properties/map: property map view.',
            '/student/requests: booking requests list.',
            '/student/onboarding: tenant onboarding status and document uploads.',
            '/student/payments: tenant monthly payments.',
            '/student/reports: submit and track concerns.',
            '/student/profile: profile management.',
            '/student/setup: student verification setup.',
            '/landlord/setup: landlord setup profile/billing (permit optional).',
            '/landlord/dashboard: landlord overview.',
            '/landlord/properties: property management.',
            '/landlord/rooms: rooms overview.',
            '/landlord/bookings: booking requests.',
            '/landlord/tenants: active tenants list.',
            '/landlord/onboarding: review tenant onboarding.',
            '/landlord/payments: manage tenant payments and reminders.',
            '/landlord/leave-requests: approve/reject leave requests.',
            '/landlord/maintenance: maintenance management.',
            '/landlord/analytics: analytics and performance.',
            '/landlord/feedback: tenant feedback review.',
            '/admin/dashboard: admin overview.',
            '/admin/settings: admin settings.',
            '/admin/users: user management.',
            '/admin/student-verifications: approve/reject student verification.',
            '/admin/permits: review landlord permits.',
            '/admin/properties: property monitoring.',
            '/admin/properties/approval: property approval queue.',
            '/admin/bookings: booking monitoring.',
            '/admin/boarded-students: boarded students list.',
            '/admin/onboardings: onboarding monitoring.',
            '/admin/reports: reports management.',
        ],
        'faq_dictionary' => [
            'Where can I browse rooms? -> /student/rooms',
            'Where do I submit a booking request? -> open a room and use the booking action.',
            'Where do I upload onboarding documents? -> /student/onboarding',
            'Where do I submit payments? -> /student/payments',
            'Where do I submit reports? -> /student/reports',
        ],
        'policy_rules' => [
            'Role-scoped access: do not guide users to actions outside their role.',
            'Business permit is optional for landlords and not a blocker for operations.',
            'Students with active approved bookings cannot submit another booking.',
            'Student verification can lock booking until approved.',
        ],
        'response_style' => [
            'Be concise and action-oriented.',
            'When asked "where" or "saan makikita", include the route path.',
            'If blocked by role, explain and point to the correct role or admin.',
        ],
        'blocked_hints' => [
            'student: no landlord/admin actions.',
            'landlord: no student/admin actions.',
            'admin: no landlord/student actions.',
        ],
    ],
    'blocked_hints' => [
        'student' => ['landlord', 'admin'],
        'landlord' => ['admin', 'student'],
        'admin' => ['landlord', 'student'],
    ],
];
